version: '3.8'
services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_chatbot_backend
    ports:
      - "0.0.0.0:8000:8000"  # Host port:container port
    volumes:
      - ./:/app:ro           # Attach code volume as read-only
      - app_data:/data       # Persistent volume for data    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # Container will be stopped by the Jenkins pipeline after 5 minutes

volumes:
  app_data:  # Define the volume
