version: '3.8'
services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/frontend  # Mount the existing frontend directory
      - app_data:/data               # Persistent volume for data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb+srv://ahmadzafar:IUzvD9FvjOjHoqPR@devops.fzvip.mongodb.net/
      - DEBUG=1
    # Container will be stopped by the Jenkins pipeline after 5 minutes

volumes:
  app_data:  # Define the volume
