# Step 1: Base Image Choose Karna (Python Image)
FROM python:3.11

# Step 2: Working Directory Set Karna
WORKDIR /app

# Step 3: Local Python files ko Docker container mein copy karna
COPY . .

# Step 4: Python Dependencies Install Karna
RUN pip install -r requirements.txt

# Step : Backend app ko run karna
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000:8000"]

