version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Backend Dockerfile specify karo
    ports:
      - "5000:5000"  # Expose Backend Port

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Frontend Dockerfile specify karo
    ports:
      - "80:80"  # Expose Frontend Port
