# Step 1: Use Nginx as a base image
FROM nginx:alpine

# Step 2: Copy frontend HTML files into Nginx's default folder
COPY ./frontend /usr/share/nginx/html

# Step 3: Expose Frontend Port (Usually Nginx uses port 80)
EXPOSE 80
