version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-assistant
    ports:
      - "8000:8000"
    volumes:
      - .:/app       # Attach source code as a volume
    restart: unless-stopped
